<a href="https://colab.research.google.com/github/JunnieLee/data_science_tutorials/blob/master/Intro_to_Data_Analysis_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [1] Numpy Arrays

- numpy basics

- https://blog.naver.com/heunghari/221445512331 

In [0]:
import numpy as np

# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])


In [2]:
# Accessing elements
    print(countries[0])
    print(countries[3])

Afghanistan
Angola


In [3]:
# Slicing
print(countries[0:3])
print(countries[:3])
print(countries[17:]) 
print(countries[:]) 

['Afghanistan' 'Albania' 'Algeria']
['Afghanistan' 'Albania' 'Algeria']
['Bhutan' 'Bolivia' 'Bosnia and Herzegovina']
['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Argentina' 'Armenia'
 'Australia' 'Austria' 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh'
 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia'
 'Bosnia and Herzegovina']


In [4]:
# Element types
print(countries.dtype)
print(employment.dtype)
print(np.array([0, 1, 2, 3]).dtype)
print(np.array([1.0, 1.5, 2.0, 2.5]).dtype)
print(np.array([True, False, True]).dtype)
print(np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype)

<U22
float64
int64
float64
bool
<U2


In [5]:
# Looping
for country in countries:
  print('Examining country {}'.format(country))

for i in range(len(countries)):
  country = countries[i]
  country_employment = employment[i]
  print('Country {} has employment {}'.format(country,country_employment))

Examining country Afghanistan
Examining country Albania
Examining country Algeria
Examining country Angola
Examining country Argentina
Examining country Armenia
Examining country Australia
Examining country Austria
Examining country Azerbaijan
Examining country Bahamas
Examining country Bahrain
Examining country Bangladesh
Examining country Barbados
Examining country Belarus
Examining country Belgium
Examining country Belize
Examining country Benin
Examining country Bhutan
Examining country Bolivia
Examining country Bosnia and Herzegovina
Country Afghanistan has employment 55.70000076
Country Albania has employment 51.40000153
Country Algeria has employment 50.5
Country Angola has employment 75.69999695
Country Argentina has employment 58.40000153
Country Armenia has employment 40.09999847
Country Australia has employment 61.5
Country Austria has employment 57.09999847
Country Azerbaijan has employment 60.90000153
Country Bahamas has employment 66.59999847
Country Bahrain has employmen

In [6]:
# Numpy functions
print(employment.mean()) 
print(employment.std())
print(employment.max())
print(employment.sum())

58.68500003850001
9.338269113687888
75.69999695
1173.70000077


In [0]:
def max_employment(countries, employment):   
  max_country = None      
  max_employment = 0   
  
  for i in range(len(contries)):
    country = countries[i]
    country_employment = employment[i]
    
    if country_employment > max_employment:
      max_country = country
      max_employment = country_employment
    
  return (max_country, max_value)

In [0]:
def max_employment(countries, employment):
  i = employment.argmax() # returns the index where the max value is located
  return (countries[i], employment[i])

# [2]  Vectorized Operations

In [9]:
# Arithmetic operations between 2 NumPy arrays

import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 1, 2])
    
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)


[2 4 4 6]
[0 0 2 2]
[1 4 3 8]
[1. 1. 3. 2.]
[ 1  4  3 16]


In [10]:
# Arithmetic operations between a NumPy array and a single number

a = np.array([1, 2, 3, 4])
b = 2

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** b)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [11]:
# Logical operations with NumPy arrays

a = np.array([True, True, False, False])
b = np.array([True, False, True, False])

print(a & b)
print(a | b)
print(~a)
print(a & True)
print(a & False)
print(a | True)
print(a | False)

[ True False False False]
[ True  True  True False]
[False False  True  True]
[ True  True False False]
[False False False False]
[ True  True  True  True]
[ True  True False False]


In [12]:
# Comparison operations between 2 NumPy Arrays

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])

print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a == b)
print(a != b)

[False False False  True  True]
[False False  True  True  True]
[ True  True False False False]
[ True  True  True False False]
[False False  True False False]
[ True  True False  True  True]


In [13]:
# Comparison operations between a NumPy array and a single number

a = np.array([1, 2, 3, 4])
b = 2
    
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
print(a == b)
print(a != b)

[False False  True  True]
[False  True  True  True]
[ True False False False]
[ True  True False False]
[False  True False False]
[ True False  True  True]


In [0]:
# First 20 countries with school completion data
countries = np.array([
       'Algeria', 'Argentina', 'Armenia', 'Aruba', 'Austria','Azerbaijan',
       'Bahamas', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Bolivia',
       'Botswana', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
       'Cambodia', 'Cameroon', 'Cape Verde'
])

# Female school completion rate in 2007 for those 20 countries
female_completion = np.array([
    97.35583,  104.62379,  103.02998,   95.14321,  103.69019,
    98.49185,  100.88828,   95.43974,   92.11484,   91.54804,
    95.98029,   98.22902,   96.12179,  119.28105,   97.84627,
    29.07386,   38.41644,   90.70509,   51.7478 ,   95.45072
])

# Male school completion rate in 2007 for those 20 countries
male_completion = np.array([
     95.47622,  100.66476,   99.7926 ,   91.48936,  103.22096,
     97.80458,  103.81398,   88.11736,   93.55611,   87.76347,
    102.45714,   98.73953,   92.22388,  115.3892 ,   98.70502,
     37.00692,   45.39401,   91.22084,   62.42028,   90.66958
])

def overall_completion_rate(female_completion, male_completion):
    return (female_completion + male_completion)/2

In [15]:
overall_completion_rate(female_completion, male_completion)

array([ 96.416025, 102.644275, 101.41129 ,  93.316285, 103.455575,
        98.148215, 102.35113 ,  91.77855 ,  92.835475,  89.655755,
        99.218715,  98.484275,  94.172835, 117.335125,  98.275645,
        33.04039 ,  41.905225,  90.962965,  57.08404 ,  93.06015 ])

In [18]:
def standardize_data(values):
    return (values - values.mean())/values.std()
  
print(sorted(standardize_data(employment)))

[-1.9901976846285574, -1.872402590419114, -1.0799647606768548, -0.8765007667751364, -0.7801229992206772, -0.565950546526159, -0.3196523083838568, -0.20185762217293615, -0.1697318367251522, -0.03051941478986332, -0.03051941478986332, 0.18365303790465493, 0.23719615107828448, 0.30144772304471396, 0.8475873135738095, 0.8797135091618392, 1.008216653094698, 1.254515301377246, 1.383018445310105, 1.822071810562803]


In [19]:
# Using index arrays

a = np.array([1, 2, 3, 4])
b = np.array([True, True, False, False])
    
print(a[b])
print(a[np.array([True, False, True, False])])

[1 2]
[1 3]


In [20]:
# Creating the index array using vectorized operations

a = np.array([1, 2, 3, 2, 1])
b = (a >= 2)

print(a[b])
print(a[a >= 2])

[2 3 2]
[2 3 2]


In [21]:
# Creating the index array using vectorized operations on another array

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 2, 3, 2, 1])
    
print(b == 2) 
print(a[b == 2])

[False  True False  True False]
[2 4]


In [0]:
# Time spent in the classroom in the first week for 20 students
time_spent = np.array([
       12.89697233,    0.        ,   64.55043217,    0.        ,
       24.2315615 ,   39.991625  ,    0.        ,    0.        ,
      147.20683783,    0.        ,    0.        ,    0.        ,
       45.18261617,  157.60454283,  133.2434615 ,   52.85000767,
        0.        ,   54.9204785 ,   26.78142417,    0.
])

# Days to cancel for 20 students
days_to_cancel = np.array([
      4,   5,  37,   3,  12,   4,  35,  38,   5,  37,   3,   3,  68,
     38,  98,   2, 249,   2, 127,  35
])

In [23]:
def mean_time_for_paid_students(time_spent, days_to_cancel):
    return time_spent[days_to_cancel >= 7].mean()

mean_time_for_paid_students(time_spent, days_to_cancel)

41.05400348545454

# [2] Pandas Series

- pandas basics
- https://blog.naver.com/heunghari/221445585994 

In [0]:
import pandas as pd

countries = ['Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda',
             'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan',
             'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
             'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia']

life_expectancy_values = [74.7,  75. ,  83.4,  57.6,  74.6,  75.4,  72.3,  81.5,  80.2,
                          70.3,  72.1,  76.4,  68.1,  75.2,  69.8,  79.4,  70.8,  62.7,
                          67.3,  70.6]

gdp_values = [ 1681.61390973,   2155.48523109,  21495.80508273,    562.98768478,
              13495.1274663 ,   9388.68852258,   1424.19056199,  24765.54890176,
              27036.48733192,   1945.63754911,  21721.61840978,  13373.21993972,
                483.97086804,   9783.98417323,   2253.46411147,  25034.66692293,
               3680.91642923,    366.04496652,   1175.92638695,   1132.21387981]

# Life expectancy and gdp data in 2007 for 20 countries
life_expectancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)

In [25]:
# Accessing elements and slicing
print(life_expectancy[0])
print(gdp[3:6])

74.7
3      562.987685
4    13495.127466
5     9388.688523
dtype: float64


In [26]:
# Looping

for country_life_expectancy in life_expectancy:
  print('Examining life expectancy {}'.format(country_life_expectancy))

Examining life expectancy 74.7
Examining life expectancy 75.0
Examining life expectancy 83.4
Examining life expectancy 57.6
Examining life expectancy 74.6
Examining life expectancy 75.4
Examining life expectancy 72.3
Examining life expectancy 81.5
Examining life expectancy 80.2
Examining life expectancy 70.3
Examining life expectancy 72.1
Examining life expectancy 76.4
Examining life expectancy 68.1
Examining life expectancy 75.2
Examining life expectancy 69.8
Examining life expectancy 79.4
Examining life expectancy 70.8
Examining life expectancy 62.7
Examining life expectancy 67.3
Examining life expectancy 70.6


In [27]:
# Pandas functions
print(life_expectancy.mean())
print(life_expectancy.std())
print(gdp.max())
print(gdp.sum())

72.86999999999999
6.213999474869968
27036.48733192
182957.59832967006


In [30]:
# Vectorized operations and index arrays

a = pd.Series([1, 2, 3, 4])
b = pd.Series([1, 2, 1, 2])
 
print(a + b, '\n')
print(a * 2, '\n')
print(a >= 3, '\n')
print(a[a >= 3], '\n')

0    2
1    4
2    4
3    6
dtype: int64 

0    2
1    4
2    6
3    8
dtype: int64 

0    False
1    False
2     True
3     True
dtype: bool 

2    3
3    4
dtype: int64 



In [0]:
# 양의 상관관계? 음의 상관관계?

def variable_correlation(variable1, variable2):
  
  both_above = (variable1 > variable1.mean()) & (variable2 > variable2.mean())
  both_below = (variable1 < variable1.mean()) & (variable2 < variable2.mean())
  
  is_same_direction = both_above | both_below  
  num_same_direction = is_same_direction.sum() 
  num_different_direction = len(variable1) - num_same_direction
    
  return (num_same_direction, num_different_direction)

In [33]:
variable_correlation(life_expectancy, gdp)

(17, 3)

In [0]:
countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola',
    'Argentina', 'Armenia', 'Australia', 'Austria',
    'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
    'Barbados', 'Belarus', 'Belgium', 'Belize',
    'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
]


employment_values = [
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076,
]

# Employment data in 2007 for 20 countries
employment = pd.Series(employment_values, index=countries)

In [0]:
def max_employment(employment):
  max_country = employment.idxmax() 
  max_value = employment.loc[max_country] # 딕셔너리 key로 value 찾는것처럼 !
  return (max_country, max_value)

In [40]:
max_employment(employment)

('Angola', 75.69999695)

In [41]:
# Addition when indexes are the same

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

print(s1 + s2)

a    11
b    22
c    33
d    44
dtype: int64


In [42]:
# Indexes have same elements in a different order

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['b', 'd', 'a', 'c'])

print(s1 + s2)

a    31
b    12
c    43
d    24
dtype: int64


In [43]:
# Indexes overlap, but do not have exactly the same elements

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])

print(s1 + s2)

a     NaN
b     NaN
c    13.0
d    24.0
e     NaN
f     NaN
dtype: float64


In [44]:
# Indexes do not overlap

s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['e', 'f', 'g', 'h'])
    
print(s1 + s2)

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
f   NaN
g   NaN
h   NaN
dtype: float64


- values are matched up based on index not position
- if the indexes don't match, NaN will be filled in.

In [47]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])

sum_result = s1 + s2

sum_result.dropna() # all the missing values (The ones with NaN) will be removed!

#  If you want to save the results of your operations for later, 
# remember to assign the results to a variable or, 
# for some Pandas functions like .dropna(), 
# use inplace = True to modify the starting object without needing to reassign it.

c    13.0
d    24.0
dtype: float64

In [49]:
# Alternate solution : Treat missing values as 0 before the addition 

s1.add(s2, fill_value = 0)

a     1.0
b     2.0
c    13.0
d    24.0
e    30.0
f    40.0
dtype: float64

In [50]:
s = pd.Series([1, 2, 3, 4, 5])

def add_one(x):
  return x + 1

print(s.apply(add_one)) # apply --> map 메소드랑 비슷함. 
                        # 요소 하나하나마다 함수를 적용시킨 값을 반환하는거

0    2
1    3
2    4
3    5
4    6
dtype: int64


In [53]:
names = pd.Series([
    'Andre Agassi',
    'Barry Bonds',
    'Christopher Columbus',
    'Daniel Defoe',
    'Emilio Estevez',
    'Fred Flintstone',
    'Greta Garbo',
    'Humbert Humbert',
    'Ivan Ilych',
    'James Joyce',
    'Keira Knightley',
    'Lois Lane',
    'Mike Myers',
    'Nick Nolte',
    'Ozzy Osbourne',
    'Pablo Picasso',
    'Quirinus Quirrell',
    'Rachael Ray',
    'Susan Sarandon',
    'Tina Turner',
    'Ugueth Urbina',
    'Vince Vaughn',
    'Woodrow Wilson',
    'Yoji Yamada',
    'Zinedine Zidane'
])


def reverse(word):  
  return word.split()[1]+', '+word.split()[0]

def reverse_names(names):
  return names.apply(reverse)

reverse_names(names)

0             Agassi, Andre
1              Bonds, Barry
2     Columbus, Christopher
3             Defoe, Daniel
4           Estevez, Emilio
5          Flintstone, Fred
6              Garbo, Greta
7          Humbert, Humbert
8               Ilych, Ivan
9              Joyce, James
10         Knightley, Keira
11               Lane, Lois
12              Myers, Mike
13              Nolte, Nick
14           Osbourne, Ozzy
15           Picasso, Pablo
16       Quirrell, Quirinus
17             Ray, Rachael
18          Sarandon, Susan
19             Turner, Tina
20           Urbina, Ugueth
21            Vaughn, Vince
22          Wilson, Woodrow
23             Yamada, Yoji
24         Zidane, Zinedine
dtype: object

In [54]:
reverse(names.iloc[0])

'Agassi, Andre'

# [3] Plotting in Pandas

If the variable data is a NumPy array or a Pandas Series, just like if it is a list, the code

 **import matplotlib.pyplot as plt**
 
**plt.hist(data)** 


will create a histogram of the data.

Pandas also has built-in plotting that uses matplotlib behind the scenes, so if data is a Series, you can create a histogram using **data.hist()**.



There's no difference between these two in this case, but sometimes the Pandas wrapper can be more convenient. For example, you can make a line plot of a series using **data.plot()**. The index of the Series will be used for the x-axis and the values for the y-axis.


---



- If you're running plotting code locally, you may need to add the line plt.show() depending on your setup.